상세한건 DOCUMENT를 보자

- 파이썬에서 변수에 변수를 넣게?되면 메모리를 공유하는 ShallowCopy가 일어남
  <br>ex) val2 = val1
- df2 = df.copy() 하면됨

### 파일 읽기

```python
with open("C:/open_data_key.txt", 'r', encoding='utf-8') as f:
    ServiceKey = f.read()
# 여러줄일 때
with open("C:/content.txt", 'r', encoding='utf-8') as f:
    content = f.readlines()
```

### 특수문자 제거
```python
content = [x.strip() for x in content]
# space로 구분되있는거 배열로 만들기
content = [x.split(' ') for x in content]
```

### print 시 공백없이 출력하는 방법
- sep='' 를 뒤에 추가해주면 됨
```python
for x in content:
    print("test",x[0],"'ㅇㅇ'", x[1], sep='')
```

### 문자열 합치기
```python
output = []
for x in content:
    temp = "data.find_all('"+x[0]+"')[0]      #"+x[1]
    output.append(temp)
```

### for문에서 key, value 값으로 나누기
```python
for k, v in enumerate(output):
    print(k, v)
```

# OS
`import os` 해서 씀

### 디렉토리 생성
```python
dir_path = "폴더를 생성하고 싶은 경로"
dir_name = "폴더 이름
os.mkdir(dir_path + "/" + dir_name + "/")
```

# requests

### URL Encode 방지
- requests 모듈 이용시 %가 %25로 인코딩되서 씀

```python
params = "&".join("%s=%s" % (k,v) for k,v in params.items())
data = requests.get(url, params)
```

# numpy

### 각 행과 열을 바꿔버리는 방법
- loadtxt의 unpack 매개변수와 transpose는 각 행을 열로 바꾸어버림

```python
data = np.loadtxt('./data.csv'
                  ,delimiter=','
                  ,uppack=True
                  ,dtype='float32'
                 )
transpose_data = np.transpose(data)
```

### 행과 열 합치는 방법
- 기본 데이터 셋

```python
x = np.array([[1.0,2.0],[3.0,4.0]])
y = np.array([[5.0,6.0],[7.0,8.0]])
```
- 행 합치는 방법 axis = 0

```python
print(np.concatenate((x,y),axis = 0))
# 결과
[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
```
- 열 합치는 방법 axis = 1

```python
print(np.concatenate((x,y),axis = 1))
# 결과
[[1. 2. 5. 6.]
 [3. 4. 7. 8.]]
```

### 로그스케일링
- log는 exp의 역함수(곱셈의 역함수는 나눗셈)
- 0의 로그 마이너스 무한대. 음수는 없다
- 위의 이유로 인해 0이 있다면 오류가 생기기 때문에 로그스케일링할때 +1을 해줌
- numpy에서는 알아서 잘 해주는듯
```python
np.log1p(200000)
np.expm1(12.206077645517674)
```

# sklearn

### train_set test_set 나누는 방법
- train 70%, test 30%

```python
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=2019)
```

### One Hot Encoding
```python
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(data)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
```

# pandas
```python
import pandas as pd
```

### dataframe 잘릴때 여러개 보고싶은 경우
```pd.set_option('display.max_columns', 30)```

### loc iloc 차이
- .iloc
<br>integer positon를 통해 값을 찾을 수 있다. label로는 찾을 수 없다
- .loc
<br>label 을 통해 값을 찾을 수 있다. integer position로는 찾을 수 없다.


### 중복제거한 항목을 보고 싶을 때 drop_duplicates()
```python
df[['col1','col2']].drop_duplicates()
```

### 컬럼별 상태 보고 싶을때
- df.dtypes

### 특정컬럼 형태 변환
- dataframe to (int or str)

```python
df['col1'] = df['col1'].apply(int)
df['col2'] = df['col2'].apply(str)
```

### 검색하기
```python
df[(df['col1']==search_condition1) & (df['col2']==search_condition2)]
```